### ISSUE TITLE
Support multiple regions for init

### ISSUE THREAD

**Issue by mlehner616** [promptworks/aws-secrets#15]
When executing the following with `AWS_DEFAULT_REGION` or the profile region either empty or anything other than us-east-1 I receive the error below.
```
aws-secrets-init-resources promptworks_test
```

> An error occurred (IllegalLocationConstraintException) when calling the CreateBucket operation: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.

**Comment by bduggan** [comment]
Thanks for the report!  This should now be possible by setting `AWS_SECRETS_BUCKET_REGION`.  The region setting apparently only affects which endpoints are used, but not where the buckets are stored.
