### ISSUE TITLE
Env file is larger than 4096 bytes

### ISSUE THREAD

**Issue by alexdrans** [promptworks/aws-secrets#21]
Hi,

Not really directly related to this useful repo, but KMS has a limit of 4KB, and my env file has exceeded this now. Has this happened to anyone else? Is the next step storing it in S3?

**Comment by bduggan** [comment]
Glad to hear it's useful!  I haven't experienced this, but it looks like the recommended next step is to contact aws support -- 
> All AWS KMS objects have limits that apply to each region and each AWS account. If you need to
> exceed these limits, please visit the AWS Support Center and create a case.

http://docs.aws.amazon.com/kms/latest/developerguide/limits.html
